x=read.table("household_power_consumption.txt",head=1,sep=";")
x.sub=x[x$Date=="1/2/2007"|x$Date=="2/2/2007",]
x.DateTime = strptime(paste(x.sub$Date, x.sub$Time), format="%d/%m/%Y %H:%M:%S")
x.sub2=data.frame(Datetime=x.DateTime,x.sub[,3:9])
png(filename="plot3.png",width = 480, height = 480, units = "px", bg="transparent")
plot(x.sub2$Datetime,as.numeric(as.character(x.sub2$Sub_metering_1)),pch=NA,xlab=NA,ylab="Energy sub metering")
lines(x.sub2$Datetime,as.numeric(as.character(x.sub2$Sub_metering_1)))
lines(x.sub2$Datetime,as.numeric(as.character(x.sub2$Sub_metering_2)),col="red")
lines(x.sub2$Datetime,as.numeric(as.character(x.sub2$Sub_metering_3)),col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,lwd=1,col=c("black","red","blue"))
dev.off()