x=read.table("household_power_consumption.txt",head=1,sep=";")
x.sub=x[x$Date=="1/2/2007"|x$Date=="2/2/2007",]
x.DateTime = strptime(paste(x.sub$Date, x.sub$Time), format="%d/%m/%Y %H:%M:%S")
x.sub2=data.frame(Datetime=x.DateTime,x.sub[,3:9])
png(filename="plot4.png",width = 480, height = 480, units = "px", bg="transparent")
par(mfrow=c(2,2))
with(x.sub2,{
plot(Datetime,as.numeric(as.character(Global_active_power)),pch=NA,xlab=NA,ylab="Global Active Power")
lines(Datetime,as.numeric(as.character(Global_active_power)))
plot(Datetime,as.numeric(as.character(Voltage)),pch=NA,xlab="datetime",ylab="Voltage")
lines(Datetime,as.numeric(as.character(Voltage)))
plot(Datetime,as.numeric(as.character(Sub_metering_1)),pch=NA,xlab=NA,ylab="Energy sub metering")
lines(Datetime,as.numeric(as.character(Sub_metering_1)))
lines(Datetime,as.numeric(as.character(Sub_metering_2)),col="red")
lines(Datetime,as.numeric(as.character(Sub_metering_3)),col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n",lty=1,lwd=1,col=c("black","red","blue"))
plot(Datetime,as.numeric(as.character(Global_reactive_power)),pch=NA,xlab="datetime",ylab="Global_reactive_power")
lines(Datetime,as.numeric(as.character(Global_reactive_power)))
})
dev.off()